steps:
  # Step 1: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy", "--quiet"]
    dir: "." # Replace with the path to your app.yaml if it's in a subdirectory

timeout: "900s" # 15 minutes timeout, adjust as needed

# (Optional) Substitute variables for dynamic settings
substitutions:
  _SERVICE_NAME: "appengine.googleapis.com" # You can define custom variables, though this is typically not needed here

# Specify the App Engine environment (standard or flexible)
options:
  env: ["standard"] # 'standard' or 'flexible' for the App Engine environment
  logging: CLOUD_LOGGING_ONLY
